### ISSUE TITLE
Not compatible with 1.0

### ISSUE THREAD

**Issue by Mythos** [php-flasher/flasher-livewire#2]
Hey there,

dependabot suggested updating the npm packages `@flasher/flasher` and `@flasher/flasher-toastr` to version 1.0.

Unfortunately, this package is not compatible with it as I get this error message:

```
Uncaught TypeError: Flasher.getInstance is not a function
```

Which is called here: https://github.com/php-flasher/flasher-livewire/blob/ee9e10746ed9d2f73b904661c4be76e906f834ea/LivewireResponseManager.php#L40

**Comment by yoeunes** [comment]
Hello @Mythos thanks for using PHPFlasher, I forget to mention it in the documentation but the v1.0 has some breaking change, now the livewire adapter is included directly inside https://packagist.org/packages/php-flasher/flasher-laravel

```bash
 composer require php-flasher/flasher-laravel
```

```js
 // this syntax is deprecated
Flasher.getInstance() 

// use this instead
flasher.render(event.detail)

// or if you want to show some message from js 
flasher.info('Welcome back');
flasher.error('Oops! Something went wrong!');
flasher.warning('Are you sure you want to proceed ?');
flasher.success('Data has been saved successfully!');

// for custom adapter like toastr
var toastrFactory = flasher.create("toastr");
toastrFactory.info('Welcome back');
toastrFactory.error('Oops! Something went wrong!');
toastrFactory.warning('Are you sure you want to proceed ?');
toastrFactory.success('Data has been saved successfully!');
```

**Comment by yoeunes** [comment]
Please check my PR on your repository and tell me if it's working correctly : https://github.com/Mythos/books/pull/158

**Comment by Mythos** [comment]
Hey there, thanks a lot for providing the PR and assisting in upgrading!

Unfortunately, I'm getting these errors:
![grafik](https://user-images.githubusercontent.com/416568/169070868-11095816-b262-4d2f-a1c4-851c68ab68ce.png)

The same happens when injecting the `ToastrFactory $flasher` as described in the docs.

**Comment by yoeunes** [comment]
Hello, It's my pleasure.
Can you tell me which route you're getting this error from or how I can reproduce it, please ?

**Comment by Mythos** [comment]
This happens for example after hitting the Update Button or changing the volume statuses in the `ShowSeries` component.
One is using the livewire version, the other one the normal one as it refreshes the page.

![grafik](https://user-images.githubusercontent.com/416568/169095150-e04848a4-699f-4d80-b645-07c21703b41b.png)

![grafik](https://user-images.githubusercontent.com/416568/169095185-ab9d2354-819c-40fb-a790-e591cf67d597.png)


This is where you find the two actions:

![grafik](https://user-images.githubusercontent.com/416568/169094864-489ca2f7-6e67-41f0-89c6-6493db9cb5a4.png)

If you'd like to try it, I've uploaded a little demo database: [books.zip](https://github.com/php-flasher/flasher-livewire/files/8718222/books.zip)

Login credentials are:
```
user@example.com
admin123
```

**Comment by yoeunes** [comment]
Can you please verify again , I just pushed some modifications : 

![Screenshot from 2022-05-18 18-21-20](https://user-images.githubusercontent.com/10859693/169104798-769ebc19-a918-4732-9043-0bf09560bfed.png)

**Comment by Mythos** [comment]
The former livewire() calls are working great now!

The ones without livewire() aren't, unfortunately.
This can be reproduced when you press "Update" on the left or go to the edit symbol (or via `mangas/books/spy-x-family/edit` in the URL) and save afterwards.
In both cases it should go tho the route in the screenshot (via redirect / reload) and display a message.

**Comment by yoeunes** [comment]
I see the problem clearly now, thank you for the details.
I just pushed the v1.0.4 which solve this redirection problem, can you check please ?

https://github.com/Mythos/books/pull/158

**Comment by Mythos** [comment]
Thank you so much, it works now!

**Comment by yoeunes** [comment]
You're welcome ^^
